FROM debian:buster-slim

RUN apt-get update && apt-get install -y openssh-server tzdata rsyslog && \
    ln -s /bin/bash /bin/rbash && \
    echo "/bin/rbash" >> /etc/shells && \
    cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime && \
    echo "Asia/Tokyo" > /etc/timezone && \
    apk del tzdata && \
    rm -rf /var/cache/apk/*

COPY sshd_config /etc/ssh/sshd_config

EXPOSE 22

CMD ["/usr/sbin/sshd", "-De"]
